// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAX09IJgLOokxhiP4ktKFwngFusq9u44Mo',
    appId: '1:71149107752:web:a19e666acaee91a784931d',
    messagingSenderId: '71149107752',
    projectId: 'catchnews8',
    authDomain: 'catchnews8.firebaseapp.com',
    storageBucket: 'catchnews8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAfjBTqLqhwdWQeb60qSVotKVYJCn2bck',
    appId: '1:71149107752:android:a93fa19e85ecf15184931d',
    messagingSenderId: '71149107752',
    projectId: 'catchnews8',
    storageBucket: 'catchnews8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1qD_yZJWLL-_lDarNnSDMoqXqz-dNyRY',
    appId: '1:71149107752:ios:5e49933f8538a5d084931d',
    messagingSenderId: '71149107752',
    projectId: 'catchnews8',
    storageBucket: 'catchnews8.firebasestorage.app',
    iosBundleId: 'com.example.catchNews',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1qD_yZJWLL-_lDarNnSDMoqXqz-dNyRY',
    appId: '1:71149107752:ios:5e49933f8538a5d084931d',
    messagingSenderId: '71149107752',
    projectId: 'catchnews8',
    storageBucket: 'catchnews8.firebasestorage.app',
    iosBundleId: 'com.example.catchNews',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAX09IJgLOokxhiP4ktKFwngFusq9u44Mo',
    appId: '1:71149107752:web:3d48c7684110150b84931d',
    messagingSenderId: '71149107752',
    projectId: 'catchnews8',
    authDomain: 'catchnews8.firebaseapp.com',
    storageBucket: 'catchnews8.firebasestorage.app',
  );
}